name: y_storiers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_bloc: ^7.0.1
  overlay_support: ^1.2.1
  shared_preferences: ^2.0.7
  provider: ^6.0.1
  path_provider: ^2.0.9
  story_time: ^1.0.6
  scale_button: ^2.1.2
  camera: ^0.9.4+21
  flutter_staggered_grid_view: ^0.6.1
  video_player: ^2.4.5
  image_picker: ^0.8.5+2
  dio: ^4.0.4
  skeleton_text: ^3.0.0
  photo_manager: ^2.1.0+2
  easy_mask: ^2.0.1
  heic_to_jpg: ^0.1.3
  flutter_image_compress: ^1.1.0
  video_compress: ^3.1.0
  date_format: ^2.0.6
  cached_network_image: ^3.2.0
  firebase_core: ^1.17.0
  neon_circular_timer: ^0.0.7
  firebase_messaging: ^11.4.0
  cloud_firestore: ^3.1.16 
  rounded_loading_button: ^2.1.0
  firebase_auth: ^3.3.18
  mime: ^1.0.2
  cached_video_player: ^2.0.3
  permission_handler: ^8.1.2
  cached_video_preview: ^1.0.6
  inview_notifier_list: ^3.0.0
  zoom_pinch_overlay: ^1.2.0
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: SF UI
      fonts:
        - asset: fonts/main_font.ttf
